name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          chmod +x gradlew
          ./gradlew --no-daemon -Pversion=${VERSION} publish
